baseURL = 'https://blog.withme.top/'
languageCode = 'en-us'
title = "withme blog"
theme = 'hugo-theme-terminal'
copyright = "withme"

[params]
readMore = "read more"
fullWidthTheme = false
centerTheme = true
subtitle = "withme blog"
keywords = "blog"
[params.Logo]
logoText = 'withme'

[permalinks]
[permalinks.page]
posts = '/:slug/'
